services:
  app:
    build:
      args:
        - DOCKER_USER=${DOCKER_USER:-user}
        - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      context: .
    env_file:
      - .env.docker.dist
      - .env.docker.local
    volumes:
      - ".:/var/www/html:cached"
      - "./tests/coverage:/opt/phpstorm-coverage:cached"
    hostname: serializer-bundle

  mysql:
    image: mysql:8
    command:
      - --default-authentication-plugin=mysql_native_password
      - --disable-log-bin
    env_file:
      - .env.docker.dist
      - .env.docker.local
    volumes:
      - mysql_data:/var/lib/mysql:cached
    ports:
      - ${MYSQL_DOCKER_PORT:-3426}:3306
    hostname: mysql

volumes:
  mysql_data:
    driver: local

networks:
  default:
